### ISSUE TITLE
[FEATURE] Treat other_hostnames and local_interfaces as list

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/exim-formula#14]

**Comment by myii** [comment]
> #### Optional: How can this template be improved?
> \

@n-rodriguez: What template?!

**Comment by n-rodriguez** [comment]
?

**Comment by myii** [comment]
@n-rodriguez I was joking with you.  That was your response to the `feature_request` template that was nicely laid out!

**Comment by n-rodriguez** [comment]
> @n-rodriguez I was joking with you. That was your response to the `feature_request` template that was nicely laid out!

Ok ^^

**Comment by myii** [comment]
@n-rodriguez The template did show up, didn't it?  Or is there some underlying issue we need to fix?

**Comment by n-rodriguez** [comment]
> @n-rodriguez The template did show up, didn't it?

It did!

**Comment by myii** [comment]
OK, thanks for that confirmation.  Sorry for the noise!

**Comment by n-rodriguez** [comment]
> OK, thanks for that confirmation. Sorry for the noise!

No problem. Tell me when  you're done with https://github.com/saltstack-formulas/exim-formula/pull/13. I've got another one to submit :)

**Comment by myii** [comment]
> No problem. Tell me when you're done with #13. I've got another one to submit :)

@n-rodriguez You're definitely keeping me busy!  I'll try to look at it within the next day.

**Comment by myii** [comment]
@n-rodriguez I just tried to ping you on IRC.  Since we're deeply entwined with all of these PRs, can we get some sort of direct contact working?  It would be easier to deal with certain issues.

One question, completely off-topic for this issue but at an organisational level: what Ruby linter would you recommend that we include in the Travis `lint` stage, for our InSpec files?

**Comment by myii** [comment]
@n-rodriguez I've started testing running linting checks with `rubocop` and it's looking good.  Any thoughts?

**Comment by n-rodriguez** [comment]
>  Any thoughts?

`rubocop` is the way to go :+1:

**Comment by myii** [comment]
@n-rodriguez These are the changes for the `template-formula` -- what do you think?

* https://github.com/myii/template-formula/compare/85118deeb9a3...88bc3c22c297
* https://travis-ci.org/myii/template-formula/builds/594008188

**Comment by n-rodriguez** [comment]
> @n-rodriguez These are the changes for the `template-formula` -- what do you think?

I'm not for running linters first. If linters don't pass, tests don't run :/

Why not adding `rubocop` in the `Gemfile`?

**Comment by myii** [comment]
> I'm not for running linters first. If linters don't pass, tests don't run :/

@n-rodriguez The linters is just an idea of mine, more to do with a pragmatic solution to our limited shared resources on Travis.  Many times, we've got complete test runs completing, even though each of them is going to fail because of lint issues.  That's not a finalised plan, though.

> Why not adding `rubocop` in the `Gemfile`?

Yes, that will be the final plan, I was just messing around for now.

The important thing: what about the actual changes made?  Are you happy with those or is there some things that could be done differently?
