### ISSUE TITLE
Rewrite formula

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/exim-formula#8]
@myii @aboe76 What do you think if I completely rewrite this formula?

**Comment by blbradley** [comment]
Why don't you just write your own?

**Comment by myoung34** [comment]
This repo contains 2 actual salt files: init.sls and map.jinja

Does it not work? If it doesnt work, a rewrite that fixes it is fairly common.
Does it work? If so what's the purpose/What are you trying to achieve?

**Comment by n-rodriguez** [comment]
https://github.com/saltstack-formulas/template-formula

**Comment by n-rodriguez** [comment]
* https://github.com/saltstack-formulas/template-formula/blob/develop/docs/TOFS_pattern.rst
* kitchen tests with multi-distros
* default pillars
* and so on

**Comment by myoung34** [comment]
Again: what are you trying to achieve? 

I dont think anyone would argue that a rewrite to make it up to date is bad, but is it worth the effort? There's 1 PR and 2 issues on a repo that hasnt been updated in 4 years, so kitchen testing and default pillars arent exactly considered "priority"

If you want to: go for it but there are plenty of other more active salt formulas that need love

**Comment by n-rodriguez** [comment]
> If you want to: go for it but there are plenty of other more active salt formulas that need love

yeah, that's why I worked on them for the last 6 months (checkout my PRs ;)

This formula was on my list of 'things to get done' and I'm reaching the end of the list.

**Comment by n-rodriguez** [comment]
> There's 1 PR and 2 issues on a repo that hasnt been updated in 4 years, so kitchen testing and default pillars arent exactly considered "priority"

Your opinion. The fact that this repo hasnt been updated in 4 years clearly shows this formula needs love.

**Comment by aboe76** [comment]
@n-rodriguez I don't mind if you want to rewrite the formula, and bring it up to same level as the `template-formula`. Have fun, and if you want a PR merged just ping me.

@myoung34 You maybe right that there are more then enough formula's that need this love, but If somebody want to do it let them.

**Comment by aboe76** [comment]
@n-rodriguez maybe @McPcholkin wants to help out too.

**Comment by myoung34** [comment]
I said that from the beginning. No one is going to argue a rewrite is bad. Just suggesting that other repos might benefit from priority

**Comment by myoung34** [comment]
Since the consensus is: sure, there are no outstanding issues in this. Ill close it as "solved" in lieu of a PR that does the work

**Comment by aboe76** [comment]
@myoung34, you are right, but having somebody wanting to the work is the hard part.

**Comment by myii** [comment]
Genuinely intrigued here and not being sarcastic in any way.

> Why don't you just write your own?

@blbradley Have a second `exim-formula`?

> If you want to: go for it but there are plenty of other more active salt formulas that need love

> ... Just suggesting that other repos might benefit from priority

@myoung34 I would appreciate a prioritised list of formulas to be worked on.  Would you mind listing a few of them here?

> What do you think if I completely rewrite this formula?

@n-rodriguez Go for it, look forward to your PR.

> ... but having somebody wanting to the work is the hard part.

@aboe76 You're absolutely right.

**Comment by blbradley** [comment]
Sure! The best formula for a task does not have to be restricted to the `saltstack-formulas` account/namespace.

**Comment by myii** [comment]
@blbradley Sure, that could be said of all formulas.  I've come across various arguments on Slack, suggesting that SaltStack Formulas aren't always fit for purpose.  I appreciate the points made there.  However, I strongly assert that formulas that aren't peer-reviewed will suffer from defects, that aren't necessarily apparent.  So if there is going to be any collaborative work to improve things over time, where better than under the SaltStack Formulas organisation?

**Comment by n-rodriguez** [comment]
The goal is also to feed this list : https://github.com/saltstack-formulas/template-formula/blob/develop/docs/CONTRIBUTING.rst#semantic-release-formulas

A lot of work has been done this summer to make it growing : 

* adding Kitchen tests
* semantic (and auto) releases
* deprecation warnings
* finding and improving some development patterns (tofs, map.jinja, repository pattern, toml config files)
* multi-distros testing

To be honest I use most of the formulas of this list in production except this one.

I don't use Postfix (too complicated for what I do) but Exim with this formula : https://github.com/jerrykan/exim-formula. 

The idea was to merge the best of all in a single one, tested formula under the `saltstack-formulas` organization :)

**Comment by myii** [comment]
@n-rodriguez Are you still planning to rewrite this?  Be aware that @vutny has approved #7, so that will probably be merged first.

**Comment by n-rodriguez** [comment]
> @n-rodriguez Are you still planning to rewrite this?

I don't know. The reaction was very hostile from people I've never worked with (in the past year) and suddenly wake up and remember there is an opened PR since 1 year.

Where were they when we worked on tofs, kitchen and other stuff on the other formulas?

 To be very honest, I really **hate** this kind of behavior.

**Comment by myii** [comment]
@n-rodriguez I'll admit, I was also a little taken aback.  But it's always good to keep an open mind, which is why I requested to continue the discussion.  There's a lot to be gained from hearing the other point of view on developments.  Some ideas have been seen as overly complex, which has saved us from investing effort unnecessarily.

@blbradley @myoung34 I've had a fairly significant hand in the changes that have been taking place in this organisation over the last nine months or so.  I absolutely welcome constructive criticism, so I would love to hear from you, if there are any concerns about how things are proceeding.  A lot of the discussions surrounding these developments have taken place in the SaltStack Formulas Slack room, which is also available via. IRC or Matrix.  Feel free to reach out here or there.

**Comment by myoung34** [comment]
The reaction was never hostile, this is just due to reading messages and losing context.

The original issue was asking to rewrite this. I followed up by asking if there were issues with the current state of the module to get the issue better written or to see if @n-rodriguez simply wanted to rewrite it for learning purposes.

It went downhill from there. I apologize if it came out this way, but if you'll re-read my replies with that in mind I simply wanted to scope out the reason for this issue being opened as opposed to simply forking it and doing the work. 

My constructive criticism is simply that we all need to work on issue templates so that this can be resolved with  better tickets. Asking a question for permission to rewrite should be on slack/irc and issues are for actionable issues that come from a template to avoid opinionated replies/out of context readings

**Comment by myii** [comment]
Thanks for the reply @myoung34.

> The reaction was never hostile, this is just due to reading messages and losing context.
> ...
> It went downhill from there. I apologize if it came out this way, but if you'll re-read my replies with that in mind I simply wanted to scope out the reason for this issue being opened as opposed to simply forking it and doing the work.

I did re-read it before [my comment above](https://github.com/saltstack-formulas/exim-formula/issues/8#issuecomment-532180378) and I can definitely see how things got misread.

> My constructive criticism is simply that we all need to work on issue templates so that this can be resolved with better tickets.

Brilliant idea and we've got an open issue about this here:

* https://github.com/saltstack-formulas/template-formula/issues/70

Would you be happy to propose something?  Once we've got something in place, I can easily propagate it to the other formulas, using the `ssf-formula`.

> Asking a question for permission to rewrite should be on slack/irc and issues are for actionable issues that come from a template to avoid opinionated replies/out of context readings

The unfortunate part is that we're not really that active on Slack/IRC/Matrix, so GitHub tends to be the main communication channel.  Perhaps the issues template can cover both/all circumstances, so that the type of issue is clearly stated.  I.e. Along the lines of:

* Feature request
* Bug report
* General query

Or whatever is more appropriate.

**Comment by myii** [comment]
> ... A lot of the discussions surrounding these developments have taken place in the SaltStack Formulas Slack room, which is also available via. IRC or Matrix. Feel free to reach out here or there.

vs.

> The unfortunate part is that we're not really that active on Slack/IRC/Matrix, so GitHub tends to be the main communication channel. Perhaps the issues template can cover both/all circumstances, so that the type of issue is clearly stated. I.e. Along the lines of:

And to add to the confusion, are these snippets from my comments above -- one minute I'm advocating the Slack room and then next minute I'm saying that nobody's around!  To clarify, the room _used to be_ much more active a few months back but it's become much quieter recently.  Everyone seems to be pretty busy so GitHub _has become_ the main place we communicate these days.  I'm still around on Slack, so that's why I suggested that as an option in the first comment.

**Comment by aboe76** [comment]
@myoung34 thanks for clarifying, GitHub issue comments are harder to read and easily mistaken.

@n-rodriguez I still hope you would take it on, and I love that you use saltstack-formulas in production.

**Comment by n-rodriguez** [comment]
```yml
    gitfs_remotes:
      - https://github.com/saltstack-formulas/apt-formula.git
      - https://github.com/saltstack-formulas/apt-cacher-formula.git
      - https://github.com/saltstack-formulas/bind-formula.git
      - https://github.com/saltstack-formulas/cron-formula.git
      - https://github.com/saltstack-formulas/fail2ban-formula.git
      - https://github.com/saltstack-formulas/grafana-formula.git
      - https://github.com/saltstack-formulas/keepalived-formula.git
      - https://github.com/saltstack-formulas/locale-formula.git
      - https://github.com/saltstack-formulas/logrotate-formula.git
      - https://github.com/saltstack-formulas/mysql-formula.git
      - https://github.com/saltstack-formulas/nfs-formula.git
      - https://github.com/saltstack-formulas/nginx-formula.git
      - https://github.com/saltstack-formulas/openssh-formula.git
      - https://github.com/saltstack-formulas/openvpn-formula.git
      - https://github.com/saltstack-formulas/packages-formula.git
      - https://github.com/saltstack-formulas/php-formula.git
      - https://github.com/saltstack-formulas/postgres-formula.git
      - https://github.com/saltstack-formulas/redis-formula.git
      - https://github.com/saltstack-formulas/resolver-formula.git
      - https://github.com/saltstack-formulas/rkhunter-formula.git
      - https://github.com/saltstack-formulas/salt-formula.git
      - https://github.com/saltstack-formulas/sudoers-formula.git
      - https://github.com/saltstack-formulas/sysctl-formula.git
      - https://github.com/saltstack-formulas/syslog-ng-formula.git
      - https://github.com/saltstack-formulas/systemd-formula.git
      - https://github.com/n-rodriguez/telegraf-formula.git
      - https://github.com/saltstack-formulas/timezone-formula.git
      - https://github.com/saltstack-formulas/ufw-formula.git
      - https://github.com/saltstack-formulas/users-formula.git
      - https://github.com/saltstack-formulas/vim-formula.git
      - https://github.com/saltstack-formulas/vsftpd-formula.git
      - https://github.com/jerrykan/exim-formula.git
```

**Comment by n-rodriguez** [comment]
[`influxdb-formula`](https://github.com/n-rodriguez/influxdb-formula) is missing but I do use it too.
Formulas for Graylog, ElasticSearch and MongoDB are the next ones I plan to use.

**Comment by aboe76** [comment]
@n-rodriguez nice list of formulas, and all are running from master?

**Comment by n-rodriguez** [comment]
> @n-rodriguez nice list of formulas, and all are running from master?

Yep, with weekly highstate

**Comment by aboe76** [comment]
@n-rodriguez wow didn't know we were **_that_** stable with the formula's.

**Comment by noelmcloughlin** [comment]
@n-rodriguez  nice. are all those based off template-formula or just some?

**Comment by n-rodriguez** [comment]
> @n-rodriguez nice. are all those based off template-formula or just some?

https://github.com/saltstack-formulas/template-formula/blob/develop/docs/CONTRIBUTING.rst#semantic-release-formulas

Each formula has it's own history, but they are progressively converging to the new standard.

**Comment by myii** [comment]
> > My constructive criticism is simply that we all need to work on issue templates so that this can be resolved with better tickets.
> 
> Brilliant idea and we've got an open issue about this here:
> 
> * [saltstack-formulas/template-formula#70](https://github.com/saltstack-formulas/template-formula/issues/70)
> 
> Would you be happy to propose something? Once we've got something in place, I can easily propagate it to the other formulas, using the `ssf-formula`.
> 
> > Asking a question for permission to rewrite should be on slack/irc and issues are for actionable issues that come from a template to avoid opinionated replies/out of context readings
> 
> The unfortunate part is that we're not really that active on Slack/IRC/Matrix, so GitHub tends to be the main communication channel. Perhaps the issues template can cover both/all circumstances, so that the type of issue is clearly stated. I.e. Along the lines of:
> 
> * Feature request
> * Bug report
> * General query
> 
> Or whatever is more appropriate.

@myoung34 So I've bitten the bullet and started https://github.com/saltstack-formulas/template-formula/pull/171.  At the time of writing, I've covered both _bug reports_ and _feature requests_.  I'm also planning to add a _pull request_ template.  Maybe we need another custom issues template, to cover situation like this one?  Would you care to look and give any feedback into the process?  Once finalised, I'm planning to push these to all of our `semantic-release` repos _en masse_ (via. the `ssf-formula`).  So it would be really helpful if we can get it decent as early as possible.
